### ISSUE TITLE
Quite mode to not print Skipped rules

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/action-datree#10]
Feature Request to add a quiet mode parameter to not print all the annotation skipped rules as they drown out any unaddressed failures:

```
+-----------------------------------+-----------------------+
| Enabled rules in policy "Default" | 20                    |
| Configs tested against policy     | 163                   |
| Total rules evaluated             | 2700                  |
| Total rules skipped               | 14                    |
| Total rules failed                | 2                     |
| Total rules passed                | 2684                  |
| See all rules in policy           | https://app.datree.io/ |
+-----------------------------------+-----------------------+
```

For an example of why this is needed, try finding the 2 failed rules in this output:

https://github.com/HariSekhon/Kubernetes-configs/runs/7407811527?check_suite_focus=true

Relates to and depends on https://github.com/datreeio/datree/issues/731

**Comment by adifayer** [comment]
Duplication of https://github.com/datreeio/datree/issues/731, closing

**Comment by HariSekhon** [comment]
@adifay I think this ticket is not a duplicate because the action needs to be updated to support a quiet mode parameter when it is added to the CLI tool?

**Comment by adifayer** [comment]
@HariSekhon Once we add the flag to the CLI, the GitHub action will support the flag out-of-the-box, therefore this task is not required :)

**Comment by HariSekhon** [comment]
I thought the action had to have a with/inputs statement support for this? [Here](https://github.com/datreeio/action-datree/blob/main/action.yaml#L4)

This is what made me think this ticket would be useful to track that change was made to expose the new quiet mode option to callers of the action...

**Comment by myishay** [comment]
I think you can use any argument you want using the `cliArguments` part.

Here is an example for using multiple cli arguments from the README:
```yaml
on:
  push:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
        
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: 'file.yaml'
          cliArguments: '--policy Staging --output simple'
```

So, once any new cli argument is added to the cli (and supported officially), you can just add it in the `cliArguments` part.

@HariSekhon does that make sense to you?
