### ISSUE TITLE
Path does not exist: datree.sarif for Pull Request from Forked Repo

### ISSUE THREAD

**Issue by berry2012** [datreeio/action-datree#27]
When running Datree workflow against a PR from a forked repo, it results in the error below:

```
Error: Path does not exist: datree.sarif
Error: Path does not exist: datree.sarif
```

From my observation, I see "No secret token is detected" in the jobs log.  

Pull requests from the same repo works and the secret token could be detected.

## My config 
```
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  k8sPolicyCheck:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: '**/*.yaml'
          cliArguments: '--only-k8s-files'

- name: Upload analysis results to GitHub
  uses: github/codeql-action/upload-sarif@v2
  with:
    sarif_file: datree.sarif
    wait-for-processing: true
```

## Ask
How to make Pull requests from forked repo work with Datree.
