### ISSUE TITLE
Globbing from doc doesn't work - results in 'stat **/*.yaml: no such file or directory'

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/action-datree#3]
The globbing example in the README section doesn't work:

https://github.com/datreeio/action-datree#examples

```yaml
      - name: Run Datree Policy Check
        uses: datreeio/action-datree@main
        with:
          path: '**/*.yaml'
```

results in:

```
stat **/*.yaml: no such file or directory
```
