### ISSUE TITLE
Disable spinner in CI as it messes up log

### ISSUE THREAD

**Issue by HariSekhon** [datreeio/action-datree#5]
Example:

![Screen Shot 2022-05-12 at 18 04 53](https://user-images.githubusercontent.com/2211051/168130103-bff50816-4cc1-402c-a63e-fa791c58c3d2.png)

**Comment by eyarz** [comment]
you can disable the spinner if you will use the `--output simple` flag when running `datree test`.
so adding this param when calling the action will do the trick:
```yaml
- name: Run Datree Policy Check
  uses: datreeio/action-datree@main
  with:
    path: 'someDirectory/someFile.yaml'
    cliArguments: '--output simple'
```
