### ISSUE TITLE
kubectl kustomize errored: error: specify one path to kustomization.yaml

### ISSUE THREAD

**Issue by prestonvanloon** [datreeio/action-datree#8]
```yaml
name: kustomization
on: push
    
env:
  DATREE_TOKEN: ${{ secrets.DATREE_TOKEN }} 

jobs:
  kustomize_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run Datree Policy Check on Kustomize
        uses: datreeio/action-datree@69aaff54675fdbda959740657d0fc81be9afd4fc
        with:
          path: 'cluster/default/**'
          isKustomization: true
          cliArguments: '--policy Github --ignore-missing-schemas --output simple'
```

> kubectl kustomize errored: error: specify one path to kustomization.yaml

It passes when using commit 460c784a6907b02041c7035a0df642a8efa17c9d
